### PR TITLE
Fix missing urandom by using OpenSSL's random_bytes

### LINKED ISSUE #233: RuntimeError: failed to get urandom on Synology DS916+ / DSM 7.2
**Describe the bug**
DaWarIch on Synology DS916+ with DSM 7.2.1-69057 Update 5 is giving a "RuntimeError: failed to get urandom" upon import of (at least GeoJSON and GPX) files.

**Version**
0.13.4

**To Reproduce**
1. Go to "Imports"
2. Click on "New import"
3. Select GPX
4. Select file
5. Click "Create import"

**Expected behavior**
The import should run through and be reported as import.

**Screenshots**
None

**Logs**
See attached log file: [dawarich_app.log](https://github.com/user-attachments/files/16918683/dawarich_app.log)

**Additional context**
None

### PR DESCRIPTION
**Pull request by saschazepter**
Fixes #233 (at least for Synology DS916+ / DSM 7.2).

### CODE REVIEW

File: config/initializers/00_random.rb [hunk 1]
```diff
@@ -0,0 +1,32 @@
+# -*- coding: us-ascii -*-
```
Comment (Freika) [inline config/initializers/00_random.rb:1]: Why is this change of encoding necessary? I'm also not sure if this is a correct way to change it :)

Comment (Freika) [reply config/initializers/00_random.rb:1]: Also, can you please add a comment on why this file is necessary? Basically, you can copy-paste the PR description. Thank you!

**Review by Freika — CHANGES_REQUESTED** [review]

File: config/initializers/00_random.rb (hunk 1 above)
Comment (saschazepter) [reply config/initializers/00_random.rb:1]: > Why is this change of encoding necessary? I'm also not sure if this is a correct way to change it :)

Another file from config/initializers has been taken as "template" for this file. So this is basically, why.

Comment (saschazepter) [reply config/initializers/00_random.rb:1]: > Also, can you please add a comment on why this file is necessary? Basically, you can copy-paste the PR description. Thank you!

Please check the issue corresponding to this pull request: this file is required to have Random::urandom(size) behave well on Docker for Synology, When running ruby/dawarich on Synology, I am getting the error "failed to get urandom". This file "replaces" the original Random::urandom(size) with a call to OpenSSL's OpenSSL::Random.random_bytes(n), which is apparently working on Docker for Synology.

Comment (Freika) [reply config/initializers/00_random.rb:1]: > Another file from config/initializers has been taken as "template" for this file. So this is basically, why.

There is no mention of `# -*- coding: us-ascii -*-` anywhere in the project, so it's safe to remove :)

> Please check the issue corresponding to this pull request: this file is required to have Random::urandom(size) behave well on Docker for Synology, When running ruby/dawarich on Synology, I am getting the error "failed to get urandom". This file "replaces" the original Random::urandom(size) with a call to OpenSSL's OpenSSL::Random.random_bytes(n), which is apparently working on Docker for Synology.

I understand, what I meant is to provide a one-line comment to describe the purpose of the file so it would be easier to understand without having to navigate to GitHub. The code fixes a very specific problem which is usually non-existent in typical Rails project, so it's good to have a small comment to make it clear why it's here.

Comment (saschazepter) [reply config/initializers/00_random.rb:1]: > I understand, what I meant is to provide a one-line comment to describe the purpose of the file so it would be easier to understand without having to navigate to GitHub. The code fixes a very specific problem which is usually non-existent in typical Rails project, so it's good to have a small comment to make it clear why it's here.

Fixes ```failed to get urandom``` for running Ruby on Docker for Synology.

OK? :)

Comment (Freika) [reply config/initializers/00_random.rb:1]: Perfect!

**Review by Freika — APPROVED** [review]
🔥

**Comment by blakeusblade** [comment]
https://github.com/maybe-finance/maybe/discussions/1554#discussioncomment-12929275
